version: '3.8'

services:
  bot:
    build: .
    container_name: telegram_bot
    environment:
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      BINANCE_API_KEY: ${BINANCE_API_KEY}
      BINANCE_API_SECRET: ${BINANCE_API_SECRET}
      CRYPTO_API_KEY: ${CRYPTO_API_KEY}
      DB_HOST: db  # Указываем имя сервиса базы данных
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      NEWSDATA_API_KEY: ${NEWSDATA_API_KEY}
      OPENSEA_API_KEY: ${OPENSEA_API_KEY}
      COINDAR_API: ${COINDAR_API}
      BITGET_API_KEY: ${BITGET_API_KEY}
      BITGET_SECRET_API_KEY: ${BITGET_SECRET_API_KEY}
      THEGRAPH_API_KEY: ${THEGRAPH_API_KEY}
      TRON_API_KEY: ${TRON_API_KEY}
      ETHERSCAN_API_KEY: ${ETHERSCAN_API_KEY}
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - db  # Зависимость от сервиса базы данных
    command: python app/main.py
    restart: unless-stopped

  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  db_data: